### ISSUE TITLE
Can't get access to sox/lame/mp3 files

### ISSUE THREAD

**Issue by gaochangw** [HPCE/hpce-2015-cw2#7]
Can't get access to URL: http://cas.ee.ic.ac.uk/people/dt10/teaching/2013/hpce/cw2/sox-14.4.1.tar.gz al well as those for lame/mp3 and the curl command didn't work.

Error page:
Access forbidden!

You don't have permission to access the requested object. It is either read-protected or not readable by the server.

If you think this is a server error, please contact the webmaster.

Error 403

cas.ee.ic.ac.uk
Sat Oct 31 20:24:52 2015
Apache

**Comment by ghost** [comment]
Hello,

You can't indeed access these resources through your web browser (for some reason), but you can get them with curl. Try out "curl http://cas.ee.ic.ac.uk/people/dt10/teaching/2013/hpce/cw2/sox-14.4.1.tar.gz > test.tar.gz" and you should have the file you need locally. The webpage probably only accept requests made from the file transfer protocol curl uses. Hope that helps !

**Comment by gaochangw** [comment]
Hi dowii,
Thank you and it works now! However, the curl command didn't indeed work yesterday.

**Comment by m8pple** [comment]
As @dowii  notes it should only be downloadable yia `curl` or `wget`.

There is a [.htaccess](https://en.wikipedia.org/wiki/.htaccess) on the directory containing the
files to force that (as otherwise people try to download it using
a web-browser, which defeats the point of the exercise).

It's possible the web-server was down over the weekend, but I'm not aware of anything. Seems
like it works now.
